// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuseumManagementSystem.Persistence;

#nullable disable

namespace MuseumManagementSystem.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240725040111_Add_Artifact_version")]
    partial class Add_Artifact_version
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("ArtifactConditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtifactTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BioDegId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Count")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ImageLink")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<string>("NewMuseumNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar");

                    b.Property<string>("OldMuseumNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<Guid?>("SafeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SerialNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Size")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<Guid?>("TimePeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactConditionId");

                    b.HasIndex("ArtifactTypeId");

                    b.HasIndex("BioDegId");

                    b.HasIndex("SafeId");

                    b.HasIndex("TimePeriodId");

                    b.ToTable("Artifacts", "Main");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.ArtifactCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("ArtifactConditions", "Main");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.ArtifactImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.ToTable("ArtifactImages", "Main");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.ArtifactMaterial", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsImportantMaterial")
                        .HasColumnType("bit");

                    b.HasKey("ArtifactId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ArtifactMaterials", "Main");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.ArtifactType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("ArtifactTypes", "Main");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.BioDeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("BioDegs", "Main");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Material", "Main");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.Safe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<Guid>("StowageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StowageId");

                    b.ToTable("Safes", "Main");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.Stowage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Stowages", "Main");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.TimePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("TimePeriods", "Main");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.Artifact", b =>
                {
                    b.HasOne("MuseumManagementSystem.Domain.Models.ArtifactCondition", "ArtifactCondition")
                        .WithMany("Artifacts")
                        .HasForeignKey("ArtifactConditionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MuseumManagementSystem.Domain.Models.ArtifactType", "ArtifactType")
                        .WithMany("Artifacts")
                        .HasForeignKey("ArtifactTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MuseumManagementSystem.Domain.Models.BioDeg", "BioDeg")
                        .WithMany("Artifacts")
                        .HasForeignKey("BioDegId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MuseumManagementSystem.Domain.Models.Safe", "Safe")
                        .WithMany("Artifacts")
                        .HasForeignKey("SafeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MuseumManagementSystem.Domain.Models.TimePeriod", "TimePeriod")
                        .WithMany("Artifacts")
                        .HasForeignKey("TimePeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ArtifactCondition");

                    b.Navigation("ArtifactType");

                    b.Navigation("BioDeg");

                    b.Navigation("Safe");

                    b.Navigation("TimePeriod");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.ArtifactImage", b =>
                {
                    b.HasOne("MuseumManagementSystem.Domain.Models.Artifact", "Artifact")
                        .WithMany("Images")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.ArtifactMaterial", b =>
                {
                    b.HasOne("MuseumManagementSystem.Domain.Models.Artifact", "Artifact")
                        .WithMany("ArtifactMaterials")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuseumManagementSystem.Domain.Models.Material", "Material")
                        .WithMany("ArtifactMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.Safe", b =>
                {
                    b.HasOne("MuseumManagementSystem.Domain.Models.Stowage", "Stowage")
                        .WithMany("Safes")
                        .HasForeignKey("StowageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stowage");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.Artifact", b =>
                {
                    b.Navigation("ArtifactMaterials");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.ArtifactCondition", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.ArtifactType", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.BioDeg", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.Material", b =>
                {
                    b.Navigation("ArtifactMaterials");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.Safe", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.Stowage", b =>
                {
                    b.Navigation("Safes");
                });

            modelBuilder.Entity("MuseumManagementSystem.Domain.Models.TimePeriod", b =>
                {
                    b.Navigation("Artifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
